In [1]:
import os
import pandas as pd

In [2]:
ruta = os.path.join("data/procesado", "dataset_dengue_con_comuna.parquet")
df = pd.read_parquet(ruta)
df

,epi_week,x,y,ndvi,tmax_fore,tmin_fore,ndwi,precip_fore,humidity,windspeed,...,windspeed_sd_4w,windspeed_max_4w,windspeed_min_4w,windspeed_mean_6w,windspeed_sd_6w,windspeed_max_6w,windspeed_min_6w,racha_precip_then_tmax_6w,nombre,comuna
0,2007-01,-76.465161,3.421354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.007623,1.014297,1.000019,1.022935,0.020961,1.052087,1.000019,0.0,Planta de Tratamiento,21
1,2007-02,-76.465161,3.421354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.008322,1.011788,1.000019,1.015647,0.015221,1.036483,1.000019,0.0,Planta de Tratamiento,21
2,2007-03,-76.465161,3.421354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.011788,1.011788,1.008701,0.007623,1.014297,1.000019,0.0,Planta de Tratamiento,21
3,2007-04,-76.465161,3.421354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.005904,0.008322,1.011788,1.000019,0.0,Planta de Tratamiento,21
4,2007-05,-76.465161,3.421354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.011788,NaN,1.011788,1.011788,0.0,Planta de Tratamiento,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131211,2025-01,-76.582161,3.457354,0.035718,27.787951,20.938776,0.142834,27.489220,90.954163,1.061518,...,0.023365,1.128455,1.074248,1.088279,0.021797,1.128455,1.065731,0.0,Sector Patio Bonito,01
131212,2025-02,-76.582161,3.457354,0.092395,28.247417,20.856209,0.140692,20.774696,90.671532,1.048811,...,0.007885,1.092650,1.074248,1.090669,0.019494,1.128455,1.074248,0.0,Sector Patio Bonito,01
131213,2025-03,-76.582161,3.457354,0.320449,29.466768,20.846842,0.097309,1.838077,90.419617,1.056752,...,0.013372,1.092650,1.061518,1.087142,0.022854,1.128455,1.061518,0.0,Sector Patio Bonito,01
131214,2025-04,-76.582161,3.457354,0.353101,30.397097,20.574366,0.076580,2.641061,90.103836,1.100131,...,0.019435,1.092650,1.048811,1.073867,0.016227,1.092650,1.048811,0.0,Sector Patio Bonito,01
131215,2025-05,-76.582161,3.457354,0.366709,30.686823,21.175499,0.108768,8.873653,89.763901,1.131289,...,0.013270,1.080075,1.048811,1.070952,0.017655,1.092650,1.048811,0.0,Sector Patio Bonito,01

In [3]:
dict(df.isnull().sum())

{'epi_week': np.int64(0),
 'x': np.int64(0),
 'y': np.int64(0),
 'ndvi': np.int64(46704),
 'tmax_fore': np.int64(46704),
 'tmin_fore': np.int64(46704),
 'ndwi': np.int64(46704),
 'precip_fore': np.int64(46426),
 'humidity': np.int64(46426),
 'windspeed': np.int64(46426),
 'band': np.int64(0),
 'slope': np.int64(46426),
 'aspect': np.int64(46426),
 'valle': np.int64(46426),
 'casos': np.int64(58797),
 'tasa_eb_100000': np.int64(61402),
 'comercial': np.int64(58797),
 'habitacional': np.int64(58797),
 'industrial': np.int64(58797),
 'institucional': np.int64(58797),
 'publico': np.int64(58797),
 'suelo_en_transformacion': np.int64(58797),
 'suelo_no_urbanizable': np.int64(58797),
 'estrato': np.int64(58797),
 'area_humedal_m2': np.int64(58797),
 'distancia_humed_m': np.int64(58797),
 'area_rio_m2': np.int64(58797),
 'distancia_rio_m': np.int64(58797),
 'distancia_pozos_m': np.int64(58797),
 'n_pozos': np.int64(58797),
 'TP34_1_EDA': np.int64(58797),
 'TP34_2_EDA': np.int64(58797),
 'TP34_3_EDA': np.int64(58797),
 'TP34_4_EDA': np.int64(58797),
 'TP34_5_EDA': np.int64(58797),
 'TP34_6_EDA': np.int64(58797),
 'TP34_7_EDA': np.int64(58797),
 'TP34_8_EDA': np.int64(58797),
 'TP34_9_EDA': np.int64(58797),
 'hacinamien': np.int64(58797),
 'n_arboles': np.int64(58797),
 'conteo': np.int64(0),
 'conteo_sumideros': np.int64(0),
 'spatial_ref': np.int64(0),
 'epi_year': np.int64(0),
 'epi_week_number': np.int64(0),
 'pixel_id': np.int64(0),
 'amplitud_termica': np.int64(46704),
 'anom_tmax': np.int64(46704),
 'anom_tmin': np.int64(46704),
 'estres_hidrico': np.int64(46704),
 'tmax_mayor_26': np.int64(0),
 'tmax_fore_lag2': np.int64(46982),
 'tmax_fore_lag3': np.int64(47121),
 'tmax_fore_lag4': np.int64(47260),
 'tmax_fore_lag5': np.int64(47399),
 'tmax_fore_lag6': np.int64(47538),
 'tmax_fore_lag7': np.int64(47677),
 'tmax_fore_mean_4w': np.int64(46299),
 'tmax_fore_sd_4w': np.int64(46573),
 'tmax_fore_max_4w': np.int64(46299),
 'tmax_fore_min_4w': np.int64(46299),
 'tmax_fore_mean_6w': np.int64(46029),
 'tmax_fore_sd_6w': np.int64(46303),
 'tmax_fore_max_6w': np.int64(46029),
 'tmax_fore_min_6w': np.int64(46029),
 'tmin_fore_lag2': np.int64(46982),
 'tmin_fore_lag3': np.int64(47121),
 'tmin_fore_lag4': np.int64(47260),
 'tmin_fore_lag5': np.int64(47399),
 'tmin_fore_lag6': np.int64(47538),
 'tmin_fore_lag7': np.int64(47677),
 'tmin_fore_mean_4w': np.int64(46299),
 'tmin_fore_sd_4w': np.int64(46573),
 'tmin_fore_max_4w': np.int64(46299),
 'tmin_fore_min_4w': np.int64(46299),
 'tmin_fore_mean_6w': np.int64(46029),
 'tmin_fore_sd_6w': np.int64(46303),
 'tmin_fore_max_6w': np.int64(46029),
 'tmin_fore_min_6w': np.int64(46029),
 'precip_fore_lag2': np.int64(46704),
 'precip_fore_lag3': np.int64(46843),
 'precip_fore_lag4': np.int64(46982),
 'precip_fore_lag5': np.int64(47121),
 'precip_fore_lag6': np.int64(47260),
 'precip_fore_lag7': np.int64(47399),
 'precip_fore_mean_4w': np.int64(46299),
 'precip_fore_sd_4w': np.int64(46573),
 'precip_fore_max_4w': np.int64(46299),
 'precip_fore_min_4w': np.int64(46299),
 'precip_fore_sum_4w': np.int64(46299),
 'precip_fore_mean_6w': np.int64(46029),
 'precip_fore_sd_6w': np.int64(46303),
 'precip_fore_max_6w': np.int64(46029),
 'precip_fore_min_6w': np.int64(46029),
 'precip_fore_sum_6w': np.int64(46029),
 'ndvi_lag2': np.int64(46982),
 'ndvi_lag3': np.int64(47121),
 'ndvi_lag4': np.int64(47260),
 'ndvi_lag5': np.int64(47399),
 'ndvi_lag6': np.int64(47538),
 'ndvi_lag7': np.int64(47677),
 'ndvi_mean_4w': np.int64(46299),
 'ndvi_sd_4w': np.int64(46573),
 'ndvi_max_4w': np.int64(46299),
 'ndvi_min_4w': np.int64(46299),
 'ndvi_mean_6w': np.int64(46029),
 'ndvi_sd_6w': np.int64(46303),
 'ndvi_max_6w': np.int64(46029),
 'ndvi_min_6w': np.int64(46029),
 'ndwi_lag2': np.int64(46982),
 'ndwi_lag3': np.int64(47121),
 'ndwi_lag4': np.int64(47260),
 'ndwi_lag5': np.int64(47399),
 'ndwi_lag6': np.int64(47538),
 'ndwi_lag7': np.int64(47677),
 'ndwi_mean_4w': np.int64(46299),
 'ndwi_sd_4w': np.int64(46573),
 'ndwi_max_4w': np.int64(46299),
 'ndwi_min_4w': np.int64(46299),
 'ndwi_mean_6w': np.int64(46029),
 'ndwi_sd_6w': np.int64(46303),
 'ndwi_max_6w': np.int64(46029),
 'ndwi_min_6w': np.int64(46029),
 'tasa_eb_100000_lag2': np.int64(61402),
 'tasa_eb_100000_lag3': np.int64(61402),
 'tasa_eb_100000_lag4': np.int64(61402),
 'tasa_eb_100000_lag5': np.int64(61402),
 'tasa_eb_100000_lag6': np.int64(61536),
 'tasa_eb_100000_lag7': np.int64(61670),
 'tasa_eb_100000_mean_4w': np.int64(61000),
 'tasa_eb_100000_sd_4w': np.int64(61268),
 'tasa_eb_100000_max_4w': np.int64(61000),
 'tasa_eb_100000_min_4w': np.int64(61000),
 'tasa_eb_100000_sum_4w': np.int64(61000),
 'tasa_eb_100000_mean_6w': np.int64(60740),
 'tasa_eb_100000_sd_6w': np.int64(61004),
 'tasa_eb_100000_max_6w': np.int64(60740),
 'tasa_eb_100000_min_6w': np.int64(60740),
 'tasa_eb_100000_sum_6w': np.int64(60740),
 'conteo_lag2': np.int64(278),
 'conteo_lag3': np.int64(417),
 'conteo_lag4': np.int64(556),
 'conteo_lag5': np.int64(695),
 'conteo_lag6': np.int64(834),
 'conteo_lag7': np.int64(973),
 'conteo_mean_4w': np.int64(8),
 'conteo_sd_4w': np.int64(12),
 'conteo_max_4w': np.int64(8),
 'conteo_min_4w': np.int64(8),
 'conteo_sum_4w': np.int64(8),
 'conteo_mean_6w': np.int64(8),
 'conteo_sd_6w': np.int64(12),
 'conteo_max_6w': np.int64(8),
 'conteo_min_6w': np.int64(8),
 'conteo_sum_6w': np.int64(8),
 'amplitud_termica_lag2': np.int64(46982),
 'amplitud_termica_lag3': np.int64(47121),
 'amplitud_termica_lag4': np.int64(47260),
 'amplitud_termica_lag5': np.int64(47399),
 'amplitud_termica_lag6': np.int64(47538),
 'amplitud_termica_lag7': np.int64(47677),
 'amplitud_termica_mean_4w': np.int64(46299),
 'amplitud_termica_sd_4w': np.int64(46573),
 'amplitud_termica_max_4w': np.int64(46299),
 'amplitud_termica_min_4w': np.int64(46299),
 'amplitud_termica_mean_6w': np.int64(46029),
 'amplitud_termica_sd_6w': np.int64(46303),
 'amplitud_termica_max_6w': np.int64(46029),
 'amplitud_termica_min_6w': np.int64(46029),
 'anom_tmax_lag2': np.int64(46982),
 'anom_tmax_lag3': np.int64(47121),
 'anom_tmax_lag4': np.int64(47260),
 'anom_tmax_lag5': np.int64(47399),
 'anom_tmax_lag6': np.int64(47538),
 'anom_tmax_lag7': np.int64(47677),
 'anom_tmax_mean_4w': np.int64(46299),
 'anom_tmax_sd_4w': np.int64(46573),
 'anom_tmax_max_4w': np.int64(46299),
 'anom_tmax_min_4w': np.int64(46299),
 'anom_tmax_mean_6w': np.int64(46029),
 'anom_tmax_sd_6w': np.int64(46303),
 'anom_tmax_max_6w': np.int64(46029),
 'anom_tmax_min_6w': np.int64(46029),
 'anom_tmin_lag2': np.int64(46982),
 'anom_tmin_lag3': np.int64(47121),
 'anom_tmin_lag4': np.int64(47260),
 'anom_tmin_lag5': np.int64(47399),
 'anom_tmin_lag6': np.int64(47538),
 'anom_tmin_lag7': np.int64(47677),
 'anom_tmin_mean_4w': np.int64(46299),
 'anom_tmin_sd_4w': np.int64(46573),
 'anom_tmin_max_4w': np.int64(46299),
 'anom_tmin_min_4w': np.int64(46299),
 'anom_tmin_mean_6w': np.int64(46029),
 'anom_tmin_sd_6w': np.int64(46303),
 'anom_tmin_max_6w': np.int64(46029),
 'anom_tmin_min_6w': np.int64(46029),
 'estres_hidrico_lag2': np.int64(46982),
 'estres_hidrico_lag3': np.int64(47121),
 'estres_hidrico_lag4': np.int64(47260),
 'estres_hidrico_lag5': np.int64(47399),
 'estres_hidrico_lag6': np.int64(47538),
 'estres_hidrico_lag7': np.int64(47677),
 'estres_hidrico_mean_4w': np.int64(46299),
 'estres_hidrico_sd_4w': np.int64(46573),
 'estres_hidrico_max_4w': np.int64(46299),
 'estres_hidrico_min_4w': np.int64(46299),
 'estres_hidrico_mean_6w': np.int64(46029),
 'estres_hidrico_sd_6w': np.int64(46303),
 'estres_hidrico_max_6w': np.int64(46029),
 'estres_hidrico_min_6w': np.int64(46029),
 'tmax_mayor_26_lag2': np.int64(278),
 'tmax_mayor_26_lag3': np.int64(417),
 'tmax_mayor_26_lag4': np.int64(556),
 'tmax_mayor_26_lag5': np.int64(695),
 'tmax_mayor_26_lag6': np.int64(834),
 'tmax_mayor_26_lag7': np.int64(973),
 'tmax_mayor_26_mean_4w': np.int64(0),
 'tmax_mayor_26_sd_4w': np.int64(0),
 'tmax_mayor_26_max_4w': np.int64(0),
 'tmax_mayor_26_min_4w': np.int64(0),
 'tmax_mayor_26_mean_6w': np.int64(0),
 'tmax_mayor_26_sd_6w': np.int64(0),
 'tmax_mayor_26_max_6w': np.int64(0),
 'tmax_mayor_26_min_6w': np.int64(0),
 'humidity_lag2': np.int64(46704),
 'humidity_lag3': np.int64(46843),
 'humidity_lag4': np.int64(46982),
 'humidity_lag5': np.int64(47121),
 'humidity_lag6': np.int64(47260),
 'humidity_lag7': np.int64(47399),
 'humidity_mean_4w': np.int64(46287),
 'humidity_sd_4w': np.int64(46565),
 'humidity_max_4w': np.int64(46287),
 'humidity_min_4w': np.int64(46287),
 'humidity_mean_6w': np.int64(46009),
 'humidity_sd_6w': np.int64(46287),
 'humidity_max_6w': np.int64(46009),
 'humidity_min_6w': np.int64(46009),
 'windspeed_lag2': np.int64(46704),
 'windspeed_lag3': np.int64(46843),
 'windspeed_lag4': np.int64(46982),
 'windspeed_lag5': np.int64(47121),
 'windspeed_lag6': np.int64(47260),
 'windspeed_lag7': np.int64(47399),
 'windspeed_mean_4w': np.int64(46287),
 'windspeed_sd_4w': np.int64(46565),
 'windspeed_max_4w': np.int64(46287),
 'windspeed_min_4w': np.int64(46287),
 'windspeed_mean_6w': np.int64(46009),
 'windspeed_sd_6w': np.int64(46287),
 'windspeed_max_6w': np.int64(46009),
 'windspeed_min_6w': np.int64(46009),
 'racha_precip_then_tmax_6w': np.int64(0),
 'nombre': np.int64(0),
 'comuna': np.int64(0)}

In [4]:
df.columns.tolist()

['epi_week',
 'x',
 'y',
 'ndvi',
 'tmax_fore',
 'tmin_fore',
 'ndwi',
 'precip_fore',
 'humidity',
 'windspeed',
 'band',
 'slope',
 'aspect',
 'valle',
 'casos',
 'tasa_eb_100000',
 'comercial',
 'habitacional',
 'industrial',
 'institucional',
 'publico',
 'suelo_en_transformacion',
 'suelo_no_urbanizable',
 'estrato',
 'area_humedal_m2',
 'distancia_humed_m',
 'area_rio_m2',
 'distancia_rio_m',
 'distancia_pozos_m',
 'n_pozos',
 'TP34_1_EDA',
 'TP34_2_EDA',
 'TP34_3_EDA',
 'TP34_4_EDA',
 'TP34_5_EDA',
 'TP34_6_EDA',
 'TP34_7_EDA',
 'TP34_8_EDA',
 'TP34_9_EDA',
 'hacinamien',
 'n_arboles',
 'conteo',
 'conteo_sumideros',
 'spatial_ref',
 'epi_year',
 'epi_week_number',
 'pixel_id',
 'amplitud_termica',
 'anom_tmax',
 'anom_tmin',
 'estres_hidrico',
 'tmax_mayor_26',
 'tmax_fore_lag2',
 'tmax_fore_lag3',
 'tmax_fore_lag4',
 'tmax_fore_lag5',
 'tmax_fore_lag6',
 'tmax_fore_lag7',
 'tmax_fore_mean_4w',
 'tmax_fore_sd_4w',
 'tmax_fore_max_4w',
 'tmax_fore_min_4w',
 'tmax_fore_mean_6w',
 'tmax_fore_sd_6w',
 'tmax_fore_max_6w',
 'tmax_fore_min_6w',
 'tmin_fore_lag2',
 'tmin_fore_lag3',
 'tmin_fore_lag4',
 'tmin_fore_lag5',
 'tmin_fore_lag6',
 'tmin_fore_lag7',
 'tmin_fore_mean_4w',
 'tmin_fore_sd_4w',
 'tmin_fore_max_4w',
 'tmin_fore_min_4w',
 'tmin_fore_mean_6w',
 'tmin_fore_sd_6w',
 'tmin_fore_max_6w',
 'tmin_fore_min_6w',
 'precip_fore_lag2',
 'precip_fore_lag3',
 'precip_fore_lag4',
 'precip_fore_lag5',
 'precip_fore_lag6',
 'precip_fore_lag7',
 'precip_fore_mean_4w',
 'precip_fore_sd_4w',
 'precip_fore_max_4w',
 'precip_fore_min_4w',
 'precip_fore_sum_4w',
 'precip_fore_mean_6w',
 'precip_fore_sd_6w',
 'precip_fore_max_6w',
 'precip_fore_min_6w',
 'precip_fore_sum_6w',
 'ndvi_lag2',
 'ndvi_lag3',
 'ndvi_lag4',
 'ndvi_lag5',
 'ndvi_lag6',
 'ndvi_lag7',
 'ndvi_mean_4w',
 'ndvi_sd_4w',
 'ndvi_max_4w',
 'ndvi_min_4w',
 'ndvi_mean_6w',
 'ndvi_sd_6w',
 'ndvi_max_6w',
 'ndvi_min_6w',
 'ndwi_lag2',
 'ndwi_lag3',
 'ndwi_lag4',
 'ndwi_lag5',
 'ndwi_lag6',
 'ndwi_lag7',
 'ndwi_mean_4w',
 'ndwi_sd_4w',
 'ndwi_max_4w',
 'ndwi_min_4w',
 'ndwi_mean_6w',
 'ndwi_sd_6w',
 'ndwi_max_6w',
 'ndwi_min_6w',
 'tasa_eb_100000_lag2',
 'tasa_eb_100000_lag3',
 'tasa_eb_100000_lag4',
 'tasa_eb_100000_lag5',
 'tasa_eb_100000_lag6',
 'tasa_eb_100000_lag7',
 'tasa_eb_100000_mean_4w',
 'tasa_eb_100000_sd_4w',
 'tasa_eb_100000_max_4w',
 'tasa_eb_100000_min_4w',
 'tasa_eb_100000_sum_4w',
 'tasa_eb_100000_mean_6w',
 'tasa_eb_100000_sd_6w',
 'tasa_eb_100000_max_6w',
 'tasa_eb_100000_min_6w',
 'tasa_eb_100000_sum_6w',
 'conteo_lag2',
 'conteo_lag3',
 'conteo_lag4',
 'conteo_lag5',
 'conteo_lag6',
 'conteo_lag7',
 'conteo_mean_4w',
 'conteo_sd_4w',
 'conteo_max_4w',
 'conteo_min_4w',
 'conteo_sum_4w',
 'conteo_mean_6w',
 'conteo_sd_6w',
 'conteo_max_6w',
 'conteo_min_6w',
 'conteo_sum_6w',
 'amplitud_termica_lag2',
 'amplitud_termica_lag3',
 'amplitud_termica_lag4',
 'amplitud_termica_lag5',
 'amplitud_termica_lag6',
 'amplitud_termica_lag7',
 'amplitud_termica_mean_4w',
 'amplitud_termica_sd_4w',
 'amplitud_termica_max_4w',
 'amplitud_termica_min_4w',
 'amplitud_termica_mean_6w',
 'amplitud_termica_sd_6w',
 'amplitud_termica_max_6w',
 'amplitud_termica_min_6w',
 'anom_tmax_lag2',
 'anom_tmax_lag3',
 'anom_tmax_lag4',
 'anom_tmax_lag5',
 'anom_tmax_lag6',
 'anom_tmax_lag7',
 'anom_tmax_mean_4w',
 'anom_tmax_sd_4w',
 'anom_tmax_max_4w',
 'anom_tmax_min_4w',
 'anom_tmax_mean_6w',
 'anom_tmax_sd_6w',
 'anom_tmax_max_6w',
 'anom_tmax_min_6w',
 'anom_tmin_lag2',
 'anom_tmin_lag3',
 'anom_tmin_lag4',
 'anom_tmin_lag5',
 'anom_tmin_lag6',
 'anom_tmin_lag7',
 'anom_tmin_mean_4w',
 'anom_tmin_sd_4w',
 'anom_tmin_max_4w',
 'anom_tmin_min_4w',
 'anom_tmin_mean_6w',
 'anom_tmin_sd_6w',
 'anom_tmin_max_6w',
 'anom_tmin_min_6w',
 'estres_hidrico_lag2',
 'estres_hidrico_lag3',
 'estres_hidrico_lag4',
 'estres_hidrico_lag5',
 'estres_hidrico_lag6',
 'estres_hidrico_lag7',
 'estres_hidrico_mean_4w',
 'estres_hidrico_sd_4w',
 'estres_hidrico_max_4w',
 'estres_hidrico_min_4w',
 'estres_hidrico_mean_6w',
 'estres_hidrico_sd_6w',
 'estres_hidrico_max_6w',
 'estres_hidrico_min_6w',
 'tmax_mayor_26_lag2',
 'tmax_mayor_26_lag3',
 'tmax_mayor_26_lag4',
 'tmax_mayor_26_lag5',
 'tmax_mayor_26_lag6',
 'tmax_mayor_26_lag7',
 'tmax_mayor_26_mean_4w',
 'tmax_mayor_26_sd_4w',
 'tmax_mayor_26_max_4w',
 'tmax_mayor_26_min_4w',
 'tmax_mayor_26_mean_6w',
 'tmax_mayor_26_sd_6w',
 'tmax_mayor_26_max_6w',
 'tmax_mayor_26_min_6w',
 'humidity_lag2',
 'humidity_lag3',
 'humidity_lag4',
 'humidity_lag5',
 'humidity_lag6',
 'humidity_lag7',
 'humidity_mean_4w',
 'humidity_sd_4w',
 'humidity_max_4w',
 'humidity_min_4w',
 'humidity_mean_6w',
 'humidity_sd_6w',
 'humidity_max_6w',
 'humidity_min_6w',
 'windspeed_lag2',
 'windspeed_lag3',
 'windspeed_lag4',
 'windspeed_lag5',
 'windspeed_lag6',
 'windspeed_lag7',
 'windspeed_mean_4w',
 'windspeed_sd_4w',
 'windspeed_max_4w',
 'windspeed_min_4w',
 'windspeed_mean_6w',
 'windspeed_sd_6w',
 'windspeed_max_6w',
 'windspeed_min_6w',
 'racha_precip_then_tmax_6w',
 'nombre',
 'comuna']

1) Agrupación y manejo de variables

### Esquema de agregación por semana epidemiológica a nivel comuna (Cali)

| **Grupo de variables** | **Agregación (Píxel a Comuna)** | **Justificación técnica y espacial** | **Ejemplos de Columnas** |
|---|---|---|---|
| Epidemiología (Absoluta) y Conteos Físicos | `sum` | Los eventos de salud y los objetos físicos (criaderos/árboles) son discretos y aditivos en el espacio. Se suman todos los píxeles para obtener la carga o capacidad vectorial total de la comuna. | `casos`, `conteo`, `conteo_sumideros`, `n_arboles`, `n_pozos`, y todos sus rezagos (`conteo_lag*`) |
| Epidemiología (Relativa) | `mean` | Ante la ausencia de denominadores poblacionales temporales, la Tasa Empírica Bayesiana se promedia espacialmente. Esta heurística es válida ya que el estimador bayesiano conserva su corrección de varianza y suavizado original. | `tasa_eb_100000`, `tasa_eb_100000_lag*` y sus ventanas móviles |
| Clima: Precipitación (Volumétrica) | `sum` | Al sumar los milímetros de lluvia de todos los píxeles, se calcula el volumen total acumulado de agua en la jurisdicción, capturando la disponibilidad hídrica real para la formación de criaderos. | `precip_fore`, `precip_fore_lag*`, `precip_fore_sum_*`|
| Clima base, derivado | `mean` | Variables continuas de naturaleza intensiva. El promedio espacial captura de manera fiel la exposición termodinámica y climática representativa de toda la zona. | `tmax_fore`, `ndvi`, `ndwi`, `amplitud_termica`,`estres_hidrico` (y sus rezagos) |
| Eventos climáticos temporales (Rachas) | `mean` | Frecuencias temporales (ej. días > 26°C). Sumarlas en el espacio excede el límite temporal de la semana. Su promedio indica la intensidad media del evento en la comuna. | `tmax_mayor_26`, `racha_precip_then_tmax_6w` (y sus rezagos) |
| Estadísticas derivadas (Dispersion/Rangos) | `mean` | Las métricas estadísticas de distribución (desviación estándar, medias, mínimos, máximos) calculadas por píxel no son aditivas en el espacio y deben promediarse para mantener coherencia. | `*_sd_*`, `*_mean_*`, `*_max_*`, `*_min_*`,(incluidas lluvias o conteos) |
| Topografía e Hidrología | `mean` | Atributos estructurales (áreas, distancias, relieves). El promedio espacial resume la morfología predominante y la exposición hídrica del territorio. | `slope`, `aspect`, `valle`, `area_humedal_m2`, `distancia_rio_m`, `distancia_pozos_m` |
| Uso del suelo y Sociodemográficas | `mean` | Variables de proporción y densidad. El promedio espacial mantiene la configuración urbana, estrato social y perfil poblacional característico de la comuna. | `comercial`, `habitacional`, `estrato`, `hacinamien`, `TP34_1_EDA` a `TP34_9_EDA` |
| Identificadores Espaciales | `Excluir` | Variables georreferenciadas a nivel de píxel pierden sentido al colapsar el área hacia un polígono administrativo. | `x`, `y`, `pixel_id`, `spatial_ref`, `band` |

#### Consideraciones estadísticas y salvaguardas en la agregación espacial

El proceso de agrupación de una malla de píxeles a límites de comuna requiere reglas matemáticas estrictas que van más allá de la división por dominios temáticos. Para garantizar la integridad del conjunto de datos multidimensional, se implementaron las siguientes salvaguardas metodológicas:

1) Manejo Dual de la Precipitación y sus Derivados: Aunque la precipitación pura y sus acumulados semanales (precip_fore, precip_fore_sum_4w) se agregan mediante suma (sum) para reflejar el volumen de agua captado por la comuna, las estadísticas derivadas de la misma lluvia (como la desviación estándar _sd_, los promedios móviles _mean_ o los valores máximos _max_) se agrupan estrictamente mediante promedio espacial (mean). Sumar varianzas o promedios en el espacio destruye la distribución estadística de la variable, por lo que el promedio espacial conserva la métrica de dispersión representativa del territorio.

2) Tratamiento de Eventos Temporales (Rachas): Las variables que contabilizan la frecuencia temporal de un evento (ej. tmax_mayor_26 o racha_precip_then_tmax_6w) no son aditivas en el espacio. Si una semana tiene 7 días, sumar las rachas de cientos de píxeles arrojaría resultados matemáticamente imposibles (ej. "700 días de calor" en una semana). Por tanto, se aplica un promedio espacial (mean), interpretándose como "la comuna experimentó un promedio de $X$ días con la condición específica".

3) Preservación del Suavizado Bayesiano: Como lineamiento operativo, las variables de incidencia relativa (Tasa de Incidencia Empírica Bayesiana - TIEB) se agregan mediante el promedio. Aunque tradicionalmente las tasas brutas requieren recálculo con denominadores poblacionales, el uso de la TIEB permite esta heurística, dado que el estimador ya penaliza intrínsecamente la inestabilidad de las varianzas en áreas pequeñas, transfiriendo este suavizado al valor promedio de la comuna.

PRECIPATACION SUMARLA PORQUE E SLA CANTDIAD DE AGUA TOTAL CAIDA EN LA ZONA, NO LA INTENSIDAD (PROMEDIO)

PERCENTILES (A DEFINIR A ULTIMOS 4 ANOS)

In [ ]:
print("Iniciando agregación espacial: Píxel -> Comuna...")

# 1. Definir llaves y variables a descartar
group_cols = ["comuna", "epi_year", "epi_week", "epi_week_number"]

# Excluimos variables de píxeles que ya no nos sirven
exclude_cols = ["x", "y", "pixel_id", "spatial_ref", "band", "nombre"]

# 2. Motor de clasificación de columnas 
sum_cols = []
mean_cols = []

# Palabras clave de ESTADÍSTICAS derivadas que NUNCA deben sumarse en el espacio
estadisticas_no_sumables = ["mean", "sd", "max", "min", "racha"]

for col in df.columns:
    # A. Saltar las llaves y las columnas excluidas
    if col in group_cols or col in exclude_cols:
        continue
        
    # B. Grupo Absoluto Directo (SUMA segura)
    if col in ["casos", "n_arboles", "n_pozos"]:
        sum_cols.append(col)
        
    # C. Familias de Conteos (SUMA) - Excluyendo sus medias y desviaciones
    elif "conteo" in col and not any(sub in col for sub in estadisticas_no_sumables):
        sum_cols.append(col)
        
    # D. Familias de Precipitación (SUMA volumétrica) - Excluyendo sus medias, desviaciones y rachas
    # Nota: Los 'precip_fore_sum_*' SI pasarán este filtro y se sumarán.
    elif "precip" in col and not any(sub in col for sub in estadisticas_no_sumables):
        sum_cols.append(col)
        
    # E. Todo lo demás: Tasa EB, Clima base, Topografía, Uso de suelo, y las Estadísticas (PROMEDIO)
    else:
        mean_cols.append(col)


# 3. Construir diccionario y tratar Nulos
# Reemplazamos el "sum" simple por una función que exige al menos 1 dato real para no sesgar datos falsos ya que sum por defecto si son nan los trata como ceros, lo que no es correcto en este caso.
agg_dict = {col: lambda x: x.sum(min_count=1) for col in sum_cols}
agg_dict.update({col: "mean" for col in mean_cols})

print(f"Plan de agregación validado:")
print(f" - {len(sum_cols)} variables a SUMA (con protección contra falsos ceros).")
print(f" - {len(mean_cols)} variables a PROMEDIO espacial/estadístico.")

# ==========================================
# 4. Ejecutar Agregación (Downgrading espacial)
print("\nCalculando agrupaciones comunales...")
df_comuna_semana = (
    df
    .groupby(group_cols, as_index=False)
    .agg(agg_dict)
)

# 5. Ordenar cronológicamente
df_comuna_semana = df_comuna_semana.sort_values(by=["comuna", "epi_year", "epi_week_number"]).reset_index(drop=True)

# 6. Guardar el resultado final
ruta_guardado = r"C:\MaestriaCienciasDatos\Semestre3\Proyecto2\data\procesado\dataset_comuna_semana.parquet"
df_comuna_semana.to_parquet(ruta_guardado, index=False)

print(f"\n¡Transformación exitosa!")
print(f"Dimensiones del nuevo dataset: {df_comuna_semana.shape} (Filas: Comuna-Semana)")
print(f"Archivo guardado y listo para Fase 4 en: \n{ruta_guardado}")

Iniciando agregación espacial: Píxel -> Comuna...
Plan de agregación validado:
 - 22 variables a SUMA (con protección contra falsos ceros).
 - 225 variables a PROMEDIO espacial/estadístico.

Calculando agrupaciones comunales...

¡Transformación exitosa!
Dimensiones del nuevo dataset: (21712, 251) (Filas: Comuna-Semana)
Archivo guardado y listo para Fase 4 en:
C:\MaestriaCienciasDatos\Semestre3\Proyecto2\data\procesado\dataset_comuna_semana.parquet

In [9]:
df_comuna_semana

,comuna,epi_year,epi_week,epi_week_number,precip_fore,casos,n_pozos,n_arboles,conteo,conteo_sumideros,...,windspeed_lag7,windspeed_mean_4w,windspeed_sd_4w,windspeed_max_4w,windspeed_min_4w,windspeed_mean_6w,windspeed_sd_6w,windspeed_max_6w,windspeed_min_6w,racha_precip_then_tmax_6w
0,01,2007,2007-01,1,NaN,NaN,NaN,NaN,0.0,328.0,...,NaN,1.015586,0.005349,1.020630,1.009995,1.025935,0.015149,1.046822,1.009995,0.0
1,01,2007,2007-02,2,NaN,NaN,NaN,NaN,0.0,328.0,...,NaN,1.013064,0.004340,1.016133,1.009995,1.020713,0.011146,1.036094,1.009995,0.0
2,01,2007,2007-03,3,NaN,NaN,NaN,NaN,1.0,328.0,...,NaN,1.016133,NaN,1.016133,1.016133,1.015586,0.005349,1.020630,1.009995,0.0
3,01,2007,2007-04,4,NaN,NaN,NaN,NaN,1.0,328.0,...,NaN,NaN,NaN,NaN,NaN,1.013064,0.004340,1.016133,1.009995,0.0
4,01,2007,2007-05,5,NaN,NaN,NaN,NaN,0.0,328.0,...,NaN,NaN,NaN,NaN,NaN,1.016133,NaN,1.016133,1.016133,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21707,81,2025,2025-01,1,1055.768593,NaN,NaN,NaN,0.0,467.0,...,0.960726,0.966217,0.009425,0.980015,0.959065,0.965111,0.007719,0.980015,0.958814,0.0
21708,81,2025,2025-02,2,830.809662,NaN,NaN,NaN,0.0,467.0,...,0.965072,0.960840,0.002639,0.963669,0.957855,0.964741,0.007990,0.980015,0.957855,0.0
21709,81,2025,2025-03,3,97.127583,NaN,NaN,NaN,0.0,467.0,...,0.980015,0.958950,0.005431,0.963669,0.951508,0.962480,0.009594,0.980015,0.951508,0.0
21710,81,2025,2025-04,4,109.655812,NaN,NaN,NaN,0.0,467.0,...,0.959065,0.955141,0.007426,0.963669,0.946884,0.956958,0.006526,0.963669,0.946884,0.0
21711,81,2025,2025-05,5,256.014819,NaN,NaN,NaN,0.0,467.0,...,0.962119,0.951690,0.004955,0.958505,0.946884,0.955425,0.006969,0.963669,0.946884,0.0

In [11]:
dict(df_comuna_semana.isnull().sum())

{'comuna': np.int64(0),
 'epi_year': np.int64(0),
 'epi_week': np.int64(0),
 'epi_week_number': np.int64(0),
 'precip_fore': np.int64(7682),
 'casos': np.int64(9729),
 'n_pozos': np.int64(9729),
 'n_arboles': np.int64(9729),
 'conteo': np.int64(0),
 'conteo_sumideros': np.int64(0),
 'precip_fore_lag2': np.int64(7728),
 'precip_fore_lag3': np.int64(7751),
 'precip_fore_lag4': np.int64(7774),
 'precip_fore_lag5': np.int64(7797),
 'precip_fore_lag6': np.int64(7820),
 'precip_fore_lag7': np.int64(7843),
 'precip_fore_sum_4w': np.int64(7659),
 'precip_fore_sum_6w': np.int64(7613),
 'conteo_lag2': np.int64(46),
 'conteo_lag3': np.int64(69),
 'conteo_lag4': np.int64(92),
 'conteo_lag5': np.int64(115),
 'conteo_lag6': np.int64(138),
 'conteo_lag7': np.int64(161),
 'conteo_sum_4w': np.int64(0),
 'conteo_sum_6w': np.int64(0),
 'ndvi': np.int64(7728),
 'tmax_fore': np.int64(7728),
 'tmin_fore': np.int64(7728),
 'ndwi': np.int64(7728),
 'humidity': np.int64(7682),
 'windspeed': np.int64(7682),
 'slope': np.int64(7682),
 'aspect': np.int64(7682),
 'valle': np.int64(7682),
 'tasa_eb_100000': np.int64(9729),
 'comercial': np.int64(9729),
 'habitacional': np.int64(9729),
 'industrial': np.int64(9729),
 'institucional': np.int64(9729),
 'publico': np.int64(9729),
 'suelo_en_transformacion': np.int64(9729),
 'suelo_no_urbanizable': np.int64(9729),
 'estrato': np.int64(9729),
 'area_humedal_m2': np.int64(9729),
 'distancia_humed_m': np.int64(9729),
 'area_rio_m2': np.int64(9729),
 'distancia_rio_m': np.int64(9729),
 'distancia_pozos_m': np.int64(9729),
 'TP34_1_EDA': np.int64(9729),
 'TP34_2_EDA': np.int64(9729),
 'TP34_3_EDA': np.int64(9729),
 'TP34_4_EDA': np.int64(9729),
 'TP34_5_EDA': np.int64(9729),
 'TP34_6_EDA': np.int64(9729),
 'TP34_7_EDA': np.int64(9729),
 'TP34_8_EDA': np.int64(9729),
 'TP34_9_EDA': np.int64(9729),
 'hacinamien': np.int64(9729),
 'amplitud_termica': np.int64(7728),
 'anom_tmax': np.int64(7728),
 'anom_tmin': np.int64(7728),
 'estres_hidrico': np.int64(7728),
 'tmax_mayor_26': np.int64(0),
 'tmax_fore_lag2': np.int64(7774),
 'tmax_fore_lag3': np.int64(7797),
 'tmax_fore_lag4': np.int64(7820),
 'tmax_fore_lag5': np.int64(7843),
 'tmax_fore_lag6': np.int64(7866),
 'tmax_fore_lag7': np.int64(7889),
 'tmax_fore_mean_4w': np.int64(7659),
 'tmax_fore_sd_4w': np.int64(7705),
 'tmax_fore_max_4w': np.int64(7659),
 'tmax_fore_min_4w': np.int64(7659),
 'tmax_fore_mean_6w': np.int64(7613),
 'tmax_fore_sd_6w': np.int64(7659),
 'tmax_fore_max_6w': np.int64(7613),
 'tmax_fore_min_6w': np.int64(7613),
 'tmin_fore_lag2': np.int64(7774),
 'tmin_fore_lag3': np.int64(7797),
 'tmin_fore_lag4': np.int64(7820),
 'tmin_fore_lag5': np.int64(7843),
 'tmin_fore_lag6': np.int64(7866),
 'tmin_fore_lag7': np.int64(7889),
 'tmin_fore_mean_4w': np.int64(7659),
 'tmin_fore_sd_4w': np.int64(7705),
 'tmin_fore_max_4w': np.int64(7659),
 'tmin_fore_min_4w': np.int64(7659),
 'tmin_fore_mean_6w': np.int64(7613),
 'tmin_fore_sd_6w': np.int64(7659),
 'tmin_fore_max_6w': np.int64(7613),
 'tmin_fore_min_6w': np.int64(7613),
 'precip_fore_mean_4w': np.int64(7659),
 'precip_fore_sd_4w': np.int64(7705),
 'precip_fore_max_4w': np.int64(7659),
 'precip_fore_min_4w': np.int64(7659),
 'precip_fore_mean_6w': np.int64(7613),
 'precip_fore_sd_6w': np.int64(7659),
 'precip_fore_max_6w': np.int64(7613),
 'precip_fore_min_6w': np.int64(7613),
 'ndvi_lag2': np.int64(7774),
 'ndvi_lag3': np.int64(7797),
 'ndvi_lag4': np.int64(7820),
 'ndvi_lag5': np.int64(7843),
 'ndvi_lag6': np.int64(7866),
 'ndvi_lag7': np.int64(7889),
 'ndvi_mean_4w': np.int64(7659),
 'ndvi_sd_4w': np.int64(7705),
 'ndvi_max_4w': np.int64(7659),
 'ndvi_min_4w': np.int64(7659),
 'ndvi_mean_6w': np.int64(7613),
 'ndvi_sd_6w': np.int64(7659),
 'ndvi_max_6w': np.int64(7613),
 'ndvi_min_6w': np.int64(7613),
 'ndwi_lag2': np.int64(7774),
 'ndwi_lag3': np.int64(7797),
 'ndwi_lag4': np.int64(7820),
 'ndwi_lag5': np.int64(7843),
 'ndwi_lag6': np.int64(7866),
 'ndwi_lag7': np.int64(7889),
 'ndwi_mean_4w': np.int64(7659),
 'ndwi_sd_4w': np.int64(7705),
 'ndwi_max_4w': np.int64(7659),
 'ndwi_min_4w': np.int64(7659),
 'ndwi_mean_6w': np.int64(7613),
 'ndwi_sd_6w': np.int64(7659),
 'ndwi_max_6w': np.int64(7613),
 'ndwi_min_6w': np.int64(7613),
 'tasa_eb_100000_lag2': np.int64(9729),
 'tasa_eb_100000_lag3': np.int64(9729),
 'tasa_eb_100000_lag4': np.int64(9729),
 'tasa_eb_100000_lag5': np.int64(9729),
 'tasa_eb_100000_lag6': np.int64(9752),
 'tasa_eb_100000_lag7': np.int64(9775),
 'tasa_eb_100000_mean_4w': np.int64(9660),
 'tasa_eb_100000_sd_4w': np.int64(9706),
 'tasa_eb_100000_max_4w': np.int64(9660),
 'tasa_eb_100000_min_4w': np.int64(9660),
 'tasa_eb_100000_sum_4w': np.int64(9660),
 'tasa_eb_100000_mean_6w': np.int64(9614),
 'tasa_eb_100000_sd_6w': np.int64(9660),
 'tasa_eb_100000_max_6w': np.int64(9614),
 'tasa_eb_100000_min_6w': np.int64(9614),
 'tasa_eb_100000_sum_6w': np.int64(9614),
 'conteo_mean_4w': np.int64(0),
 'conteo_sd_4w': np.int64(0),
 'conteo_max_4w': np.int64(0),
 'conteo_min_4w': np.int64(0),
 'conteo_mean_6w': np.int64(0),
 'conteo_sd_6w': np.int64(0),
 'conteo_max_6w': np.int64(0),
 'conteo_min_6w': np.int64(0),
 'amplitud_termica_lag2': np.int64(7774),
 'amplitud_termica_lag3': np.int64(7797),
 'amplitud_termica_lag4': np.int64(7820),
 'amplitud_termica_lag5': np.int64(7843),
 'amplitud_termica_lag6': np.int64(7866),
 'amplitud_termica_lag7': np.int64(7889),
 'amplitud_termica_mean_4w': np.int64(7659),
 'amplitud_termica_sd_4w': np.int64(7705),
 'amplitud_termica_max_4w': np.int64(7659),
 'amplitud_termica_min_4w': np.int64(7659),
 'amplitud_termica_mean_6w': np.int64(7613),
 'amplitud_termica_sd_6w': np.int64(7659),
 'amplitud_termica_max_6w': np.int64(7613),
 'amplitud_termica_min_6w': np.int64(7613),
 'anom_tmax_lag2': np.int64(7774),
 'anom_tmax_lag3': np.int64(7797),
 'anom_tmax_lag4': np.int64(7820),
 'anom_tmax_lag5': np.int64(7843),
 'anom_tmax_lag6': np.int64(7866),
 'anom_tmax_lag7': np.int64(7889),
 'anom_tmax_mean_4w': np.int64(7659),
 'anom_tmax_sd_4w': np.int64(7705),
 'anom_tmax_max_4w': np.int64(7659),
 'anom_tmax_min_4w': np.int64(7659),
 'anom_tmax_mean_6w': np.int64(7613),
 'anom_tmax_sd_6w': np.int64(7659),
 'anom_tmax_max_6w': np.int64(7613),
 'anom_tmax_min_6w': np.int64(7613),
 'anom_tmin_lag2': np.int64(7774),
 'anom_tmin_lag3': np.int64(7797),
 'anom_tmin_lag4': np.int64(7820),
 'anom_tmin_lag5': np.int64(7843),
 'anom_tmin_lag6': np.int64(7866),
 'anom_tmin_lag7': np.int64(7889),
 'anom_tmin_mean_4w': np.int64(7659),
 'anom_tmin_sd_4w': np.int64(7705),
 'anom_tmin_max_4w': np.int64(7659),
 'anom_tmin_min_4w': np.int64(7659),
 'anom_tmin_mean_6w': np.int64(7613),
 'anom_tmin_sd_6w': np.int64(7659),
 'anom_tmin_max_6w': np.int64(7613),
 'anom_tmin_min_6w': np.int64(7613),
 'estres_hidrico_lag2': np.int64(7774),
 'estres_hidrico_lag3': np.int64(7797),
 'estres_hidrico_lag4': np.int64(7820),
 'estres_hidrico_lag5': np.int64(7843),
 'estres_hidrico_lag6': np.int64(7866),
 'estres_hidrico_lag7': np.int64(7889),
 'estres_hidrico_mean_4w': np.int64(7659),
 'estres_hidrico_sd_4w': np.int64(7705),
 'estres_hidrico_max_4w': np.int64(7659),
 'estres_hidrico_min_4w': np.int64(7659),
 'estres_hidrico_mean_6w': np.int64(7613),
 'estres_hidrico_sd_6w': np.int64(7659),
 'estres_hidrico_max_6w': np.int64(7613),
 'estres_hidrico_min_6w': np.int64(7613),
 'tmax_mayor_26_lag2': np.int64(46),
 'tmax_mayor_26_lag3': np.int64(69),
 'tmax_mayor_26_lag4': np.int64(92),
 'tmax_mayor_26_lag5': np.int64(115),
 'tmax_mayor_26_lag6': np.int64(138),
 'tmax_mayor_26_lag7': np.int64(161),
 'tmax_mayor_26_mean_4w': np.int64(0),
 'tmax_mayor_26_sd_4w': np.int64(0),
 'tmax_mayor_26_max_4w': np.int64(0),
 'tmax_mayor_26_min_4w': np.int64(0),
 'tmax_mayor_26_mean_6w': np.int64(0),
 'tmax_mayor_26_sd_6w': np.int64(0),
 'tmax_mayor_26_max_6w': np.int64(0),
 'tmax_mayor_26_min_6w': np.int64(0),
 'humidity_lag2': np.int64(7728),
 'humidity_lag3': np.int64(7751),
 'humidity_lag4': np.int64(7774),
 'humidity_lag5': np.int64(7797),
 'humidity_lag6': np.int64(7820),
 'humidity_lag7': np.int64(7843),
 'humidity_mean_4w': np.int64(7659),
 'humidity_sd_4w': np.int64(7705),
 'humidity_max_4w': np.int64(7659),
 'humidity_min_4w': np.int64(7659),
 'humidity_mean_6w': np.int64(7613),
 'humidity_sd_6w': np.int64(7659),
 'humidity_max_6w': np.int64(7613),
 'humidity_min_6w': np.int64(7613),
 'windspeed_lag2': np.int64(7728),
 'windspeed_lag3': np.int64(7751),
 'windspeed_lag4': np.int64(7774),
 'windspeed_lag5': np.int64(7797),
 'windspeed_lag6': np.int64(7820),
 'windspeed_lag7': np.int64(7843),
 'windspeed_mean_4w': np.int64(7659),
 'windspeed_sd_4w': np.int64(7705),
 'windspeed_max_4w': np.int64(7659),
 'windspeed_min_4w': np.int64(7659),
 'windspeed_mean_6w': np.int64(7613),
 'windspeed_sd_6w': np.int64(7659),
 'windspeed_max_6w': np.int64(7613),
 'windspeed_min_6w': np.int64(7613),
 'racha_precip_then_tmax_6w': np.int64(0)}